-- Querion PostgreSQL Schema for Supabase
-- Version: 1.0.0
-- Purpose: AI-Powered Conversational Assistant for Secure Database Interaction

-- 1. Users Table (Authentication and Profile)
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- bcrypt hash
    role VARCHAR(50) DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Database Connections Storage
-- Stores metadata for external databases connected by users
CREATE TABLE IF NOT EXISTS database_connections (
    connection_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    database_name VARCHAR(255) NOT NULL,
    database_type VARCHAR(100) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. AI Prompts Storage
-- Stores natural language questions asked by the user
CREATE TABLE IF NOT EXISTS prompts (
    prompt_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    prompt_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Generated SQL Storage
-- Stores queries generated by AI for a specific prompt
CREATE TABLE IF NOT EXISTS generated_queries (
    query_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    prompt_id UUID REFERENCES prompts(prompt_id) ON DELETE CASCADE,
    generated_sql TEXT NOT NULL,
    execution_status VARCHAR(50) DEFAULT 'pending', -- pending, success, failed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Query Result Storage (JSONB for Flexibility)
-- Stores the JSON output of executed queries
CREATE TABLE IF NOT EXISTS query_results (
    result_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_id UUID REFERENCES generated_queries(query_id) ON DELETE CASCADE,
    result_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Dashboard Chart Data
-- Stores configuration and data for data visualizations
CREATE TABLE IF NOT EXISTS charts (
    chart_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_id UUID REFERENCES generated_queries(query_id) ON DELETE CASCADE,
    chart_type VARCHAR(50) NOT NULL CHECK (chart_type IN ('bar', 'line', 'pie')),
    chart_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Image Storage (Metadata)
-- Stores URLs for images hosted on Supabase Storage
CREATE TABLE IF NOT EXISTS images (
    image_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. Activity Logs (Security and Auditing)
-- Used for backend monitoring and audit trails
CREATE TABLE IF NOT EXISTS activity_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 9. Chat Sessions
-- Groups chatbot messages into separate conversations
CREATE TABLE IF NOT EXISTS chat_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    session_title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. Chat Messages
-- Stores individual interactions between user and assistant
CREATE TABLE IF NOT EXISTS chat_messages (
    message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    sender VARCHAR(50) NOT NULL CHECK (sender IN ('user', 'assistant')),
    message_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Performance Optimization: Standard Indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_db_conns_user_id ON database_connections(user_id);
CREATE INDEX IF NOT EXISTS idx_prompts_user_id ON prompts(user_id);
CREATE INDEX IF NOT EXISTS idx_queries_prompt_id ON generated_queries(prompt_id);
CREATE INDEX IF NOT EXISTS idx_results_query_id ON query_results(query_id);
CREATE INDEX IF NOT EXISTS idx_charts_query_id ON charts(query_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id ON chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);

-- GIN Index for JSONB data for faster searching
CREATE INDEX IF NOT EXISTS idx_query_results_data ON query_results USING GIN (result_data);
CREATE INDEX IF NOT EXISTS idx_chart_data ON charts USING GIN (chart_data);
