import os
import csv
import json
import datetime
import logging
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.units import inch
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill

logger = logging.getLogger(__name__)

class ExportEngine:
    """
    Engine for exporting reports to PDF, Excel, CSV, and JSON formats.
    """
    
    def __init__(self, base_dir: str = "reports"):
        self.base_dir = base_dir
        self.dirs = {
            "pdf": os.path.join(base_dir, "pdf"),
            "excel": os.path.join(base_dir, "excel"),
            "csv": os.path.join(base_dir, "csv"),
            "json": os.path.join(base_dir, "json")
        }
        for d in self.dirs.values():
            os.makedirs(d, exist_ok=True)

    def _get_filename(self, report_type: str, extension: str) -> str:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"report_{report_type}_{timestamp}.{extension}"

    def export_to_pdf(self, report: Dict[str, Any], full_data: List[Dict[str, Any]]) -> str:
        """
        Exports the report to a professional PDF document.
        """
        filename = self._get_filename(report["header"]["report_type"], "pdf")
        path = os.path.join(self.dirs["pdf"], filename)
        
        doc = SimpleDocTemplate(path, pagesize=letter, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
        styles = getSampleStyleSheet()
        story = []

        # Theme Colors
        PRIMARY_COLOR = colors.hexColor("#1e3a8a") # Deep Blue
        SECONDARY_COLOR = colors.hexColor("#3b82f6") # Bright Blue
        ACCENT_COLOR = colors.hexColor("#f59e0b") # Amber
        TEXT_DARK = colors.hexColor("#1f2937")

        # Custom Styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=28,
            textColor=PRIMARY_COLOR,
            spaceAfter=30,
            alignment=1,
            fontName='Helvetica-Bold'
        )
        section_style = ParagraphStyle(
            'SectionStyle',
            parent=styles['Heading2'],
            fontSize=18,
            textColor=SECONDARY_COLOR,
            spaceBefore=20,
            spaceAfter=15,
            borderPadding=10,
            leading=22
        )
        metric_card_style = ParagraphStyle(
            'MetricCardStyle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=TEXT_DARK,
            leading=14
        )
        normal_style = styles['Normal']
        normal_style.fontSize = 11
        normal_style.leading = 16

        # 1. Header & Title Section
        story.append(Paragraph(report["header"]["report_title"].upper(), title_style))
        
        # Header Info Table
        header_info = [
            [Paragraph(f"<b>Report ID:</b> {report['header']['report_id']}", normal_style), 
             Paragraph(f"<b>Date:</b> {datetime.datetime.now().strftime('%B %d, %Y')}", normal_style)],
            [Paragraph(f"<b>Generated By:</b> {report['header']['generated_by']}", normal_style),
             Paragraph(f"<b>Type:</b> {report['header']['report_type'].replace('_', ' ').title()}", normal_style)]
        ]
        h_table = Table(header_info, colWidths=[3*inch, 3*inch])
        h_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LINEBELOW', (0, 1), (-1, 1), 1, colors.lightgrey),
        ]))
        story.append(h_table)
        story.append(Spacer(1, 0.4 * inch))

        # 2. Executive Summary
        story.append(Paragraph("EXECUTIVE SUMMARY", section_style))
        summary_text = f"This comprehensive {report['header']['report_type'].replace('_', ' ')} has been automatically generated based on the query: \"{report['metadata']['user_query']}\". A total of {report['summary']['total_records']:,} records were analyzed to extract these insights."
        story.append(Paragraph(summary_text, normal_style))
        story.append(Spacer(1, 0.2 * inch))
        
        story.append(Paragraph("Key Intelligence Highlights:", styles['Heading3']))
        for finding in report['summary']['key_findings']:
            story.append(Paragraph(f"• {finding}", normal_style))
        story.append(Spacer(1, 0.3 * inch))

        # 3. Numeric Performance Metrics
        if report["metrics"]:
            story.append(Paragraph("KEY PERFORMANCE INDICATORS", section_style))
            
            # Create a grid of metric "cards"
            metrics_data = []
            current_row = []
            for i, (col, stats) in enumerate(report["metrics"].items()):
                card_content = [
                    Paragraph(f"<b>{col.upper()}</b>", metric_card_style),
                    Spacer(1, 0.05*inch),
                    Paragraph(f"Sum: <b>{stats['sum']:,.2f}</b>", metric_card_style),
                    Paragraph(f"Avg: <b>{stats['mean']:,.2f}</b>", metric_card_style),
                    Paragraph(f"Range: {stats['min']:,.2f} - {stats['max']:,.2f}", metric_card_style)
                ]
                current_row.append(card_content)
                if len(current_row) == 3 or i == len(report["metrics"]) - 1:
                    metrics_data.append(current_row)
                    current_row = []
            
            if metrics_data:
                m_table = Table(metrics_data, colWidths=[2*inch]*3)
                m_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), colors.hexColor("#f8fafc")),
                    ('BOX', (0, 0), (-1, -1), 0.5, colors.hexColor("#e2e8f0")),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('LEFTPADDING', (0, 0), (-1, -1), 10),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                    ('TOPPADDING', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ]))
                story.append(m_table)
            story.append(Spacer(1, 0.4 * inch))

        # 4. Visualizations
        if report["charts"]:
            story.append(PageBreak())
            story.append(Paragraph("VISUAL ANALYSIS", section_style))
            for chart_path in report["charts"]:
                if os.path.exists(chart_path):
                    img = Image(chart_path, width=6.5*inch, height=3.5*inch)
                    story.append(img)
                    story.append(Spacer(1, 0.3 * inch))

        # 5. Data Table
        story.append(PageBreak())
        story.append(Paragraph("DETAILED DATA RECAP", section_style))
        story.append(Paragraph("Listing the most significant records for granular review:", normal_style))
        story.append(Spacer(1, 0.1 * inch))
        
        table_data = report["data_table"]
        if table_data:
            headers = [h.replace("_", " ").title() for h in table_data[0].keys()]
            raw_headers = list(table_data[0].keys())
            data_rows = [headers]
            for row in table_data:
                data_rows.append([str(row.get(h, ""))[:30] for h in raw_headers]) # Truncate long strings
            
            col_count = len(headers)
            available_width = letter[0] - 100 # margins
            col_width = available_width / col_count
            
            t = Table(data_rows, colWidths=[col_width]*col_count, repeatRows=1)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.hexColor("#f1f5f9")]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.hexColor("#cbd5e1")),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(t)

        # 6. Final Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle('FooterStyle', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=1)
        story.append(Paragraph(f"This report is confidential and for internal use only. Generated by {report['header']['generated_by']} on {report['header']['generated_timestamp']}.", footer_style))
        story.append(Paragraph(f"Page 1 of 1 | {report['footer']['system_name']}", footer_style))

        doc.build(story)
        return path

        # 6. Footer
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph(f"--- End of Report | System: {report['footer']['system_name']} ---", normal_style))

        doc.build(story)
        return path

    def export_to_excel(self, report: Dict[str, Any], full_data: List[Dict[str, Any]]) -> str:
        """
        Exports the report to an Excel file with multiple sheets.
        """
        filename = self._get_filename(report["header"]["report_type"], "xlsx")
        path = os.path.join(self.dirs["excel"], filename)
        
        wb = Workbook()
        
        # 1. Summary Sheet
        ws_summary = wb.active
        ws_summary.title = "Report Summary"
        
        ws_summary.append(["REPORT SUMMARY"])
        ws_summary["A1"].font = Font(bold=True, size=16)
        
        ws_summary.append(["Report Title", report["header"]["report_title"]])
        ws_summary.append(["Generated At", report["header"]["generated_timestamp"]])
        ws_summary.append(["Total Records", report["summary"]["total_records"]])
        ws_summary.append([])
        
        ws_summary.append(["Key Findings"])
        ws_summary[f"A{ws_summary.max_row}"].font = Font(bold=True)
        for finding in report["summary"]["key_findings"]:
            ws_summary.append([finding])
            
        # 2. Metrics Sheet
        if report["metrics"]:
            ws_metrics = wb.create_sheet(title="Metrics")
            headers = ["Column", "Count", "Sum", "Average", "Min", "Max"]
            ws_metrics.append(headers)
            for cell in ws_metrics[1]:
                cell.font = Font(bold=True)
                cell.fill = PatternFill(start_color="CCE5FF", end_color="CCE5FF", fill_type="solid")
            
            for col, stats in report["metrics"].items():
                ws_metrics.append([
                    col, stats["count"], stats["sum"], stats["mean"], stats["min"], stats["max"]
                ])

        # 3. Data Sheet (Full Data)
        ws_data = wb.create_sheet(title="Data")
        if full_data:
            headers = list(full_data[0].keys())
            ws_data.append(headers)
            for cell in ws_data[1]:
                cell.font = Font(bold=True)
            
            for row in full_data:
                ws_data.append([row.get(h) for h in headers])
                
            # Auto-adjust column width
            for col in ws_data.columns:
                max_length = 0
                column = col[0].column_letter
                for cell in col:
                    try:
                        if len(str(cell.value)) > max_length:
                            max_length = len(str(cell.value))
                    except:
                        pass
                ws_data.column_dimensions[column].width = min(max_length + 2, 50)

        wb.save(path)
        return path

    def export_to_csv(self, report: Dict[str, Any], full_data: List[Dict[str, Any]]) -> str:
        """
        Exports the data part of the report to a CSV file.
        """
        filename = self._get_filename(report["header"]["report_type"], "csv")
        path = os.path.join(self.dirs["csv"], filename)
        
        if not full_data:
            return ""

        headers = list(full_data[0].keys())
        with open(path, mode='w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()
            writer.writerows(full_data)
            
        return path

    def export_to_json(self, report: Dict[str, Any], full_data: List[Dict[str, Any]]) -> str:
        """
        Exports the full report template and data to a JSON file.
        """
        filename = self._get_filename(report["header"]["report_type"], "json")
        path = os.path.join(self.dirs["json"], filename)
        
        full_report = report.copy()
        full_report["full_data"] = full_data # Include all data in JSON

        with open(path, 'w', encoding='utf-8') as f:
            json.dump(full_report, f, indent=4)
            
        return path
