from pymongo import MongoClient
from typing import Dict, Any, List
import json
from .base import BaseConnector

class MongoDBConnector(BaseConnector):
    def test_connection(self, credentials: Dict[str, Any]) -> Dict[str, Any]:
        uri = credentials.get('uri')
        if not uri:
            return {"success": False, "error": "Connection URI is required."}
            
        try:
            client = MongoClient(uri, serverSelectionTimeoutMS=3000) # Faster feedback
            client.server_info() # Trigger connection
            return {"success": True}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def _get_db(self, client, credentials):
        db_name = credentials.get('database')
        if not db_name:
            try:
                # Try to get default db from URI
                db_name = client.get_database().name
            except:
                # Fallback to 'test' if nothing specified
                db_name = 'test'
        return client[db_name]

    def get_schema_summary(self, credentials: Dict[str, Any]) -> str:
        uri = credentials.get('uri')
        try:
            client = MongoClient(uri)
            db = self._get_db(client, credentials)
            
            collections = db.list_collection_names()
            if not collections:
                return "The database is empty."
                
            schema_parts = []
            for coll_name in collections:
                # Sample one document to get "columns"
                doc = db[coll_name].find_one()
                if doc:
                    fields = [f"{k} ({type(v).__name__})" for k, v in doc.items()]
                    schema_parts.append(f"Collection: {coll_name}\nFields: {', '.join(fields)}")
                else:
                    schema_parts.append(f"Collection: {coll_name} (Empty)")
                    
            return "\n\n".join(schema_parts)
        except Exception as e:
            return f"Could not fetch MongoDB schema: {str(e)}"

    def execute_read_only_query(self, credentials: Dict[str, Any], query: str) -> Dict[str, Any]:
        """
        For MongoDB, the 'query' generated by AI might be a JSON aggregation or find.
        We'll expect the AI to generate a JSON string that we can parse and execute.
        """
        uri = credentials.get('uri')
        try:
            client = MongoClient(uri)
            db = self._get_db(client, credentials)
            
            # AI typically generates SQL. We might need to handle SQL-to-Mongo or 
            # expect AI to generate Mongo Shell commands. 
            # For this MVP, let's assume the AI generates a JSON blob:
            # { "collection": "...", "pipeline": [...] } or { "collection": "...", "find": {...} }
            
            try:
                q = json.loads(query)
            except:
                # If it's SQL-like, we can't execute it directly without a translator.
                # In a real app, we'd use a tool or specific prompt.
                raise Exception("MongoDB requires JSON query format for this connector.")
            
            coll_name = q.get("collection")
            if not coll_name:
                raise Exception("JSON query must specify 'collection'.")
                
            coll = db[coll_name]
            
            if "pipeline" in q:
                cursor = coll.aggregate(q["pipeline"])
            elif "find" in q:
                cursor = coll.find(q["find"], q.get("projection"))
                if q.get("limit"):
                    cursor = cursor.limit(q["limit"])
            else:
                raise Exception("JSON query must contain 'pipeline' or 'find'.")
                
            rows = []
            for doc in cursor:
                # Convert ObjectId to string
                if "_id" in doc:
                    doc["_id"] = str(doc["_id"])
                rows.append(doc)
            
            if rows:
                columns = [{"name": k, "type": "string"} for k in rows[0].keys()]
            else:
                columns = []
                
            return {
                "columns": columns,
                "rows": rows
            }
        except Exception as e:
            raise Exception(f"MongoDB Error: {str(e)}")
